global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: cadvisor
    scrape_interval: 15s
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: docker
    static_configs:
      - targets:
        - docker_exporter:9417