version: '3.9'

services:
  mqtt:
    container_name: home_mqtt
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    volumes:
      - ${ROOT_DIRECTORY}/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ${ROOT_DIRECTORY}/mqtt/data:/mosquitto/data
      - ${ROOT_DIRECTORY}/mqtt/log:/mosquitto/log
    networks:
      - frontend
      - backend
    restart: unless-stopped

  mariadb:
    container_name: home_mariadb
    image: mariadb:latest
    user: ${PUID}:${PGID}
    ports:
      - 3306:3306
    volumes:
      - ${ROOT_DIRECTORY}/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - backend
    restart: unless-stopped

  homeassistant:
    container_name: home_assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    depends_on:
      - mariadb
      - mqtt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ${LOCAL_MEDIA_DIRECTORY}:/mnt/media:ro
      - ${ROOT_DIRECTORY}/home-assistant:/config
      - ${ROOT_DIRECTORY}/home-assistant/docker/run:/etc/services.d/home-assistant/run
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PACKAGES=iputils
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - SYS_ADMIN
    network_mode: host
    restart: unless-stopped

  esphome:
    container_name: home_esphome
    image: esphome/esphome:latest
    ports:
      - 6052:6052
    volumes:
      - ${ROOT_DIRECTORY}/esphome:/config
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.backend=esphome
      - traefik.http.routers.esphome.service=esphome
      - traefik.http.routers.esphome.entrypoints=websecure
      - traefik.http.routers.esphome.rule=Host(`esphome.${LOCAL_DOMAIN}`)
      - traefik.http.routers.esphome.tls=true
    networks:
      - frontend
      - backend
    restart: unless-stopped

networks:
  frontend:
    external: true
  backend: