version: '3.9'

services:
  agent:
    container_name: management_portainer_agent
    image: portainer/agent:latest
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  portainer:
    container_name: management_portainer
    image: portainer/portainer-ce:latest
    command: -H tcp://agent:9001 --tlsskipverify
    ports:
      - 9000:9000
    volumes:
      - ${ROOT_DIRECTORY}/portainer:/data
    links:
      - agent
    restart: always