[log]
  level = "INFO"

# API and dashboard configuration
[api]
  insecure = true

[providers]
  [providers.docker]
    exposedByDefault = false
    useBindPortIP = true
  [providers.file]
    directory = "/etc/traefik/conf.d"
    watch = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"
  [entryPoints.metrics]
    address = ":8082"

[tls.stores.default.defaultCertificate]
  certFile = "/certs/cert.crt"
  keyFile = "/certs/cert.key"

[certificatesResolvers.default.acme]
  dnschallenge = true
  email = "daniel@majoinen.com"
  storage = "/letsencrypt/acme.json"
  [certificatesResolvers.default.acme.dnsChallenge]
    provider = "cloudflare"

# Metrics definition
[metrics]
  [metrics.prometheus]
    entryPoint = "metrics"